# Default initial positions for mini_mec_six_arm's ros2_control fake system

initial_positions:
  joint1: 0
  joint10: 0
  joint11: 0
  joint2: 0
  joint3: 0
  joint4: 0
  joint5: 0
  joint6: 0
  joint7: 0
  joint8: 0
  joint9: 0